PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO "undefined" VALUES(1);
CREATE TABLE 'menu' ('menu_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'id', 'value', 'undefined_id');
INSERT INTO "menu" VALUES(1,'file','File',1);
CREATE TABLE 'popup' ('popup_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'menu_id');
INSERT INTO "popup" VALUES(1,1);
CREATE TABLE 'menuitem' ('menuitem_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'value', 'onclick', 'popup_id');
INSERT INTO "menuitem" VALUES(1,'New','CreateNewDoc()',1);
INSERT INTO "menuitem" VALUES(2,'Open','OpenDoc()',1);
INSERT INTO "menuitem" VALUES(3,'Close','CloseDoc()',1);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('undefined',1);
INSERT INTO "sqlite_sequence" VALUES('menu',1);
INSERT INTO "sqlite_sequence" VALUES('popup',1);
INSERT INTO "sqlite_sequence" VALUES('menuitem',3);
COMMIT;
