CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO undefined DEFAULT VALUES;
CREATE TABLE 'glossary' ('glossary_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'glossary' ADD COLUMN 'title';
ALTER TABLE 'glossary' ADD COLUMN 'undefined_id' REFERENCES 'undefined' ('undefined_id');
INSERT INTO 'glossary' ('title','undefined_id') VALUES ('example glossary',1);
CREATE TABLE 'GlossDiv' ('GlossDiv_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'GlossDiv' ADD COLUMN 'title';
ALTER TABLE 'GlossDiv' ADD COLUMN 'glossary_id' REFERENCES 'glossary' ('glossary_id');
INSERT INTO 'GlossDiv' ('title','glossary_id') VALUES ('S',1);
CREATE TABLE 'GlossList' ('GlossList_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'GlossList' ADD COLUMN 'GlossDiv_id' REFERENCES 'GlossDiv' ('GlossDiv_id');
INSERT INTO 'GlossList' ('GlossDiv_id') VALUES (1);
CREATE TABLE 'GlossEntry' ('GlossEntry_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'GlossEntry' ADD COLUMN 'ID';
ALTER TABLE 'GlossEntry' ADD COLUMN 'SortAs';
ALTER TABLE 'GlossEntry' ADD COLUMN 'GlossTerm';
ALTER TABLE 'GlossEntry' ADD COLUMN 'Acronym';
ALTER TABLE 'GlossEntry' ADD COLUMN 'Abbrev';
ALTER TABLE 'GlossEntry' ADD COLUMN 'GlossSee';
ALTER TABLE 'GlossEntry' ADD COLUMN 'GlossList_id' REFERENCES 'GlossList' ('GlossList_id');
INSERT INTO 'GlossEntry' ('ID','SortAs','GlossTerm','Acronym','Abbrev','GlossSee','GlossList_id') VALUES ('SGML','SGML','Standard Generalized Markup Language','SGML','ISO 8879:1986','markup',1);
CREATE TABLE 'GlossDef' ('GlossDef_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'GlossDef' ADD COLUMN 'para';
ALTER TABLE 'GlossDef' ADD COLUMN 'GlossEntry_id' REFERENCES 'GlossEntry' ('GlossEntry_id');
INSERT INTO 'GlossDef' ('para','GlossEntry_id') VALUES ('A meta-markup language, used to create markup languages such as DocBook.',1);
CREATE TABLE 'GlossSeeAlso' ('GlossSeeAlso_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'GlossSeeAlso' ADD COLUMN 'GlossSeeAlso';
ALTER TABLE 'GlossSeeAlso' ADD COLUMN 'GlossDef_id' REFERENCES 'GlossDef' ('GlossDef_id');
INSERT INTO 'GlossSeeAlso' ('GlossSeeAlso','GlossDef_id') VALUES ('GML',1);
INSERT INTO 'GlossSeeAlso' ('GlossSeeAlso','GlossDef_id') VALUES ('XML',1);

