CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'undefined' ADD COLUMN 'name';
ALTER TABLE 'undefined' ADD COLUMN 'age';
INSERT INTO undefined ('name','age') VALUES ('John',30);
CREATE TABLE 'cars' ('cars_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'cars' ADD COLUMN 'name';
ALTER TABLE 'cars' ADD COLUMN 'undefined_id' REFERENCES 'undefined' ('undefined_id');
INSERT INTO 'cars' ('name','undefined_id') VALUES ('Ford',1);
INSERT INTO 'cars' ('name','undefined_id') VALUES ('BMW',1);
INSERT INTO 'cars' ('name','undefined_id') VALUES ('Fiat',1);
CREATE TABLE 'models' ('models_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'models' ADD COLUMN 'models';
ALTER TABLE 'models' ADD COLUMN 'cars_id' REFERENCES 'cars' ('cars_id');
INSERT INTO 'models' ('models','cars_id') VALUES ('Fiesta',1);
INSERT INTO 'models' ('models','cars_id') VALUES ('Focus',1);
INSERT INTO 'models' ('models','cars_id') VALUES ('Mustang',1);
INSERT INTO 'models' ('models','cars_id') VALUES ('320',2);
INSERT INTO 'models' ('models','cars_id') VALUES ('X3',2);
INSERT INTO 'models' ('models','cars_id') VALUES ('X5',2);
INSERT INTO 'models' ('models','cars_id') VALUES ('500',3);
INSERT INTO 'models' ('models','cars_id') VALUES ('Panda',3);

