PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'name', 'age');
INSERT INTO "undefined" VALUES(1,'John',30);
CREATE TABLE 'cars' ('cars_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'name', 'undefined_id' REFERENCES 'undefined' ('undefined_id'));
INSERT INTO "cars" VALUES(1,'Ford',1);
INSERT INTO "cars" VALUES(2,'BMW',1);
INSERT INTO "cars" VALUES(3,'Fiat',1);
CREATE TABLE 'models' ('models_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'models', 'cars_id' REFERENCES 'cars' ('cars_id'));
INSERT INTO "models" VALUES(1,'Fiesta',1);
INSERT INTO "models" VALUES(2,'Focus',1);
INSERT INTO "models" VALUES(3,'Mustang',1);
INSERT INTO "models" VALUES(4,'320',2);
INSERT INTO "models" VALUES(5,'X3',2);
INSERT INTO "models" VALUES(6,'X5',2);
INSERT INTO "models" VALUES(7,'500',3);
INSERT INTO "models" VALUES(8,'Panda',3);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('undefined',1);
INSERT INTO "sqlite_sequence" VALUES('cars',3);
INSERT INTO "sqlite_sequence" VALUES('models',8);
COMMIT;
