PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'batchcomplete');
INSERT INTO "undefined" VALUES(1,'');
CREATE TABLE 'continue' ('continue_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'accontinue', 'continue', 'undefined_id');
INSERT INTO "continue" VALUES(1,'List_of_Equestrian_Sports','-||',1);
CREATE TABLE 'query' ('query_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'undefined_id');
INSERT INTO "query" VALUES(1,1);
CREATE TABLE 'allcategories' ('allcategories_id' INTEGER PRIMARY KEY AUTOINCREMENT, '*', 'query_id');
INSERT INTO "allcategories" VALUES(1,'List of African-American Nonfiction Writers',1);
INSERT INTO "allcategories" VALUES(2,'List of African-American Writers',1);
INSERT INTO "allcategories" VALUES(3,'List of Albanians',1);
INSERT INTO "allcategories" VALUES(4,'List of Ambassadors of the Kingdom of the Netherlands',1);
INSERT INTO "allcategories" VALUES(5,'List of Batman characters',1);
INSERT INTO "allcategories" VALUES(6,'List of British television programmes',1);
INSERT INTO "allcategories" VALUES(7,'List of C-SPAN Q&A interviews by year',1);
INSERT INTO "allcategories" VALUES(8,'List of Chabad Houses',1);
INSERT INTO "allcategories" VALUES(9,'List of Chicago Bears Players',1);
INSERT INTO "allcategories" VALUES(10,'List of Entrepreneurs',1);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('undefined',1);
INSERT INTO "sqlite_sequence" VALUES('continue',1);
INSERT INTO "sqlite_sequence" VALUES('query',1);
INSERT INTO "sqlite_sequence" VALUES('allcategories',10);
COMMIT;
