PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'batchcomplete');
INSERT INTO "undefined" VALUES(1,'');
CREATE TABLE 'query' ('query_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'undefined_id');
INSERT INTO "query" VALUES(1,1);
CREATE TABLE 'redirects' ('redirects_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'from', 'to', 'query_id');
INSERT INTO "redirects" VALUES(1,'Main page','Main Page',1);
CREATE TABLE 'pages' ('pages_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'query_id');
INSERT INTO "pages" VALUES(1,1);
CREATE TABLE '15580374' ('15580374_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'pageid', 'ns', 'title', 'pages_id');
INSERT INTO "15580374" VALUES(1,15580374,0,'Main Page',1);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('undefined',1);
INSERT INTO "sqlite_sequence" VALUES('query',1);
INSERT INTO "sqlite_sequence" VALUES('redirects',1);
INSERT INTO "sqlite_sequence" VALUES('pages',1);
INSERT INTO "sqlite_sequence" VALUES('15580374',1);
COMMIT;
