PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO "undefined" VALUES(1);
CREATE TABLE 'menu' ('menu_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'header', 'undefined_id' REFERENCES 'undefined' ('undefined_id'));
INSERT INTO "menu" VALUES(1,'SVG Viewer',1);
CREATE TABLE 'items' ('items_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'id', 'menu_id' REFERENCES 'menu' ('menu_id'), 'label');
INSERT INTO "items" VALUES(1,'Open',1,NULL);
INSERT INTO "items" VALUES(2,'OpenNew',1,'Open New');
INSERT INTO "items" VALUES(3,NULL,1,NULL);
INSERT INTO "items" VALUES(4,'ZoomIn',1,'Zoom In');
INSERT INTO "items" VALUES(5,'ZoomOut',1,'Zoom Out');
INSERT INTO "items" VALUES(6,'OriginalView',1,'Original View');
INSERT INTO "items" VALUES(7,NULL,1,NULL);
INSERT INTO "items" VALUES(8,'Quality',1,NULL);
INSERT INTO "items" VALUES(9,'Pause',1,NULL);
INSERT INTO "items" VALUES(10,'Mute',1,NULL);
INSERT INTO "items" VALUES(11,NULL,1,NULL);
INSERT INTO "items" VALUES(12,'Find',1,'Find...');
INSERT INTO "items" VALUES(13,'FindAgain',1,'Find Again');
INSERT INTO "items" VALUES(14,'Copy',1,NULL);
INSERT INTO "items" VALUES(15,'CopyAgain',1,'Copy Again');
INSERT INTO "items" VALUES(16,'CopySVG',1,'Copy SVG');
INSERT INTO "items" VALUES(17,'ViewSVG',1,'View SVG');
INSERT INTO "items" VALUES(18,'ViewSource',1,'View Source');
INSERT INTO "items" VALUES(19,'SaveAs',1,'Save As');
INSERT INTO "items" VALUES(20,NULL,1,NULL);
INSERT INTO "items" VALUES(21,'Help',1,NULL);
INSERT INTO "items" VALUES(22,'About',1,'About Adobe CVG Viewer...');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('undefined',1);
INSERT INTO "sqlite_sequence" VALUES('menu',1);
INSERT INTO "sqlite_sequence" VALUES('items',22);
COMMIT;
