CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO undefined DEFAULT VALUES;
CREATE TABLE 'menu' ('menu_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'menu' ADD COLUMN 'header';
ALTER TABLE 'menu' ADD COLUMN 'undefined_id' REFERENCES 'undefined' ('undefined_id');
INSERT INTO 'menu' ('header','undefined_id') VALUES ('SVG Viewer',1);
CREATE TABLE 'items' ('items_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'items' ADD COLUMN 'id';
ALTER TABLE 'items' ADD COLUMN 'menu_id' REFERENCES 'menu' ('menu_id');
INSERT INTO 'items' ('id','menu_id') VALUES ('Open',1);
ALTER TABLE 'items' ADD COLUMN 'label';
INSERT INTO 'items' ('id','label','menu_id') VALUES ('OpenNew','Open New',1);
INSERT INTO 'items' ('menu_id') VALUES (1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('ZoomIn','Zoom In',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('ZoomOut','Zoom Out',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('OriginalView','Original View',1);
INSERT INTO 'items' ('menu_id') VALUES (1);
INSERT INTO 'items' ('id','menu_id') VALUES ('Quality',1);
INSERT INTO 'items' ('id','menu_id') VALUES ('Pause',1);
INSERT INTO 'items' ('id','menu_id') VALUES ('Mute',1);
INSERT INTO 'items' ('menu_id') VALUES (1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('Find','Find...',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('FindAgain','Find Again',1);
INSERT INTO 'items' ('id','menu_id') VALUES ('Copy',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('CopyAgain','Copy Again',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('CopySVG','Copy SVG',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('ViewSVG','View SVG',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('ViewSource','View Source',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('SaveAs','Save As',1);
INSERT INTO 'items' ('menu_id') VALUES (1);
INSERT INTO 'items' ('id','menu_id') VALUES ('Help',1);
INSERT INTO 'items' ('id','label','menu_id') VALUES ('About','About Adobe CVG Viewer...',1);

