CREATE TABLE 'undefined' ('undefined_id' INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO undefined DEFAULT VALUES;
CREATE TABLE 'widget' ('widget_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'widget' ADD COLUMN 'debug';
ALTER TABLE 'widget' ADD COLUMN 'undefined_id' REFERENCES 'undefined' ('undefined_id');
INSERT INTO 'widget' ('debug','undefined_id') VALUES ('on',1);
CREATE TABLE 'window' ('window_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'window' ADD COLUMN 'title';
ALTER TABLE 'window' ADD COLUMN 'name';
ALTER TABLE 'window' ADD COLUMN 'width';
ALTER TABLE 'window' ADD COLUMN 'height';
ALTER TABLE 'window' ADD COLUMN 'widget_id' REFERENCES 'widget' ('widget_id');
INSERT INTO 'window' ('title','name','width','height','widget_id') VALUES ('Sample Konfabulator Widget','main_window',500,500,1);
CREATE TABLE 'image' ('image_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'image' ADD COLUMN 'src';
ALTER TABLE 'image' ADD COLUMN 'name';
ALTER TABLE 'image' ADD COLUMN 'hOffset';
ALTER TABLE 'image' ADD COLUMN 'vOffset';
ALTER TABLE 'image' ADD COLUMN 'alignment';
ALTER TABLE 'image' ADD COLUMN 'widget_id' REFERENCES 'widget' ('widget_id');
INSERT INTO 'image' ('src','name','hOffset','vOffset','alignment','widget_id') VALUES ('Images/Sun.png','sun1',250,250,'center',1);
CREATE TABLE 'text' ('text_id' INTEGER PRIMARY KEY AUTOINCREMENT);
ALTER TABLE 'text' ADD COLUMN 'data';
ALTER TABLE 'text' ADD COLUMN 'size';
ALTER TABLE 'text' ADD COLUMN 'style';
ALTER TABLE 'text' ADD COLUMN 'name';
ALTER TABLE 'text' ADD COLUMN 'hOffset';
ALTER TABLE 'text' ADD COLUMN 'vOffset';
ALTER TABLE 'text' ADD COLUMN 'alignment';
ALTER TABLE 'text' ADD COLUMN 'onMouseUp';
ALTER TABLE 'text' ADD COLUMN 'widget_id' REFERENCES 'widget' ('widget_id');
INSERT INTO 'text' ('data','size','style','name','hOffset','vOffset','alignment','onMouseUp','widget_id') VALUES ('Click Here',36,'bold','text1',250,100,'center','sun1.opacity = (sun1.opacity / 100) * 90;',1);

